name: run tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'

      - name: Install QEMU & SSH tools
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-x86 wget unzip sshpass openssh-client

      - name: Cache CHR Image
        id: cache-chr-6.49.17
        uses: actions/cache@v6
        with:
          path: chr-6.49.17.img.zip
          key: chr-6.49.17.img.zip

      - name: Download CHR Image
        if: steps.cache-chr-6.49.17.outputs.cache-hit != 'true'
        run: |
          wget -nv https://download.mikrotik.com/routeros/6.49.17/chr-6.49.17.img.zip

      - name: Unzip Image
        run: |
          unzip -o chr-6.49.17.img.zip
